@startuml

package Model {

class Balatro {
    - rondas : List<Ronda>
    - mazo: Mazo
    - jugador: Jugador

    + Balatro(nombreJugador: string, jugador: Jugador)
    +cargarRondasDesdeJSON(rutaArchivo: string)
    + iniciarJuego()
}

class Jugador {
    - nombre: string
    - manoActual: Mano
    - mazo: Mazo
    - cartasTarot: ArrayList<Tarot>
    - comodines: ArrayList<Comodin>
    - rondaActual: Ronda

    + Jugador(nombre: string, mazo: Mazo)
    + esPosibleIniciarRonda(): boolean
    + iniciarRonda(rondaActual: Ronda)
    + jugar()
    + seleccionarCarta(unaCarta: CartaPoker)
    + aniadirTarots(cartaTarot: Tarot)
    + utilizarTarot(tarotaAplicar: Tarot, carta: CartaPoker)
    + aniadirComodin(unComodin: Comodin)
    + aplicarComodin(unaJugada: Jugada)
    + descartar()
}

class Tienda {
    - comodinesAComprar: List<Comodin>
    - tarotAComprar: List<Tarot>
    - cartasAComprar: List<CartaPoker>
    + mostrarCartas(): cartasAComprar
    + venderCarta(): Comprable
}

class Ronda {
    - Numero: int
    - PuntajeMinimo: int
    - DescartesDisponibles: int
    - JugadasDisponibles: int
    - Jugadas: List<Jugada>

    + Ronda(numero: int, PuntajeMinimo: int, descartesDisponibles: int, jugadasDisponibles: int)
    + verificarPuntaje(): boolean
    + agregarJugada(unaJugada: Jugada)
    + estadoRonda(): boolean
    + agregarDescarte(unDescarte: Descarte)
    + calcularTotalRonda(): int
}

class Panel {
    + mostrarInformacion(rondaActual: Ronda)
}

Balatro *-- Jugador
Jugador .up.> Ronda
Panel .left.> Ronda
Balatro *-- Tienda
Balatro o-- "0..8" Ronda
Balatro *-- Panel
Panel .right.> Tienda

}
@enduml