@startuml
package Model {

    class Puntaje {
        - puntos: int
        - multiplicador: int
        + Puntaje(puntos:int, multiplicador:int)
        + incrementarPuntos(incremento: int)
        + incrementarMultiplicador(incremento: int)
        + multiplicarMultiplicador(incremento: int)
        + calcularPuntaje(): int
    }

    class CartaPoker {
        - valor
        - palo
        - puntosAdicionales
        - multiplicadorAdicional
        + comprar(): CartaPoker
    }

    abstract class Jugada {
        - sumaCartas: int
        - Puntaje: Puntaje
        + Jugada(Lista<CartaPoker>)
        + {abstract} obtenerPuntaje(): Puntaje
    }

    class CartaAlta {
        + obtenerPuntaje(): Puntaje
    }

    class Par {
    + obtenerPuntaje(): Puntaje
    }

    class DoblePar {
    + obtenerPuntaje(): Puntaje
    }

    class Trio {
    + obtenerPuntaje(): Puntaje
    }

    class Escalera {
    + obtenerPuntaje(): Puntaje
    }

    class Color {
    + obtenerPuntaje(): Puntaje
    }

    class FullHouse {
    + obtenerPuntaje(): Puntaje
    }

    class Poker {
    + obtenerPuntaje(): Puntaje
    }

    class EscaleraColor {
    + obtenerPuntaje(): Puntaje
    }

    class EscaleraReal {
    + obtenerPuntaje(): Puntaje
    }

    Jugada *-up- "1..5"CartaPoker
    Jugada o-up- Puntaje

    CartaAlta -up--|> Jugada
    Par -up--|> Jugada
    DoblePar -up--|> Jugada
    Trio -up--|> Jugada
    Escalera -up--|> Jugada
    Color -up--|> Jugada
    FullHouse -up--|> Jugada
    Poker -up--|> Jugada
    EscaleraColor -up--|> Jugada
    EscaleraReal -up--|> Jugada

}
@enduml