@startuml

package Model {

class Balatro {
    - rondas : int
    - puntajeActual : int
    - rondaActual : int
    + Balatro(nombreJugador: string)
    +verificarResultado(): boolean
    + mostrarTienda()
    - iniciarRonda()
    # crearRonda(): Ronda
}

class Jugador {
    - nombre: string
    - puntaje: int
    - manoActual: Mano
    - mazo: Mazo
    - comodines: List<Comodin>
    - cartasTarot: List<Tarot>
    - cartasSeleccionadas: List<CartaPoker>
    + Jugador(nombre: string)
    + esMismoPuntaje(unPuntaje: int): boolean
    + esMismoNombre(unNombre: String): boolean
    + iniciarRonda()
    + jugar(): Jugada
    + descartarCartas()
    + comprarCartas()
    + ordenarCartas()
}

class Tienda {
    - comodinesAComprar: Lista [Comodin]
    - tarotAComprar: Lista [Tarot]
    - cartasAComprar: List[CartaPoker]]
    + mostrarCartas(): cartasAComprar
    + venderCarta(): Comprable
}

class Ronda {
    - PuntajeMinimo: int
    - DescartesDisponibles: int
    - JugadasDisponibles: int
    - PuntajeAcumulado: int
    + Ronda(jugador: Jugador)
    + iniciarRonda()
    + verificarPuntaje(): boolean
}

class Panel {
    + mostrarInformacion(rondaActual: Ronda)
}

Balatro *-- Jugador
Balatro *-- Tienda
Balatro o-- "0..8" Ronda
Balatro *-- Panel
Ronda .up.> Jugador
Panel .left.> Ronda
Panel .right.> Tienda
}
@enduml