@startuml
'https://plantuml.com/sequence-diagram

title El jugador le aplica un tarot a una carta y se le cambia el valor

actor ":TestCase" as user
participant ":Jugador" as jugador
participant "puntajeTarot:Puntaje" as puntajeTarot
participant "cartaTarot:Tarot" as tarot
participant "DosPicas:CartaPoker" as carta
participant "puntajePoker:Puntaje" as puntajePoker


user -> jugador**: Jugador(nombreJugador)
user -> puntajeTarot**: Puntaje(10,0)
user -> tarot**: Tarot(puntajeTarot)
user -> jugador: añadirTarot(cartaTarot)
user -> carta**: Carta(2, Picas)
carta -> puntajePoker**: Puntaje(2,1)

user -> jugador: utilizarTarot(0, cartaPoker)
jugador -> tarot: modificarPuntaje(cartaPoker)
tarot -> carta: modificarPuntaje(puntajeTarot)
carta -> puntajePoker: sumarPuntaje(puntajeTarot)
puntajePoker -> puntajeTarot: incrementarPuntos(2)
puntajePoker -> puntajeTarot: incrementarMultiplicador(1)
puntajePoker --> carta: puntajeModificado

user -> carta: calcularPuntaje
carta -> puntajePoker: calcularPuntaje
puntajePoker -> carta: 12
carta -> user: 12

@enduml