@startuml
'https://plantuml.com/sequence-diagram
actor Tester

Tester -> Balatro : iniciarJuego()

loop hasta completar rondas o cumplir condiciones
 Balatro -> Ronda : crearRonda()

 Ronda -> Jugador : iniciarRonda()

 Jugador -> Mazo : repartir()

 Mazo -> Mano : crear Mano con 8 cartas
 return Mano

 Mazo --> Jugador : return Mano

 Jugador -> Jugada : jugar()
 Jugada --> Jugador : return jugada creada

 Jugador --> Ronda : return Jugada

 Ronda -> Ronda : calcular puntaje acumulado
 Ronda --> Balatro : return puntaje acumulado

 Balatro -> Balatro : verificarResultado()
end

Balatro --> Tester : return juegoFinalizado
@enduml
