@startuml
'https://plantuml.com/sequence-diagram

title Se verifica que el jugador posea cartas suficientes en su mazo
actor ":TestCase" as user
participant ":Juego" as juego
participant ":Ronda" as ronda
participant ":Jugador" as jugador
participant ":Mazo" as mazo

user -> juego**: Juego(nombreJugador)
juego -> jugador**: Jugador(nombreJugador)
jugador --> mazo **: Mazo()
mazo --> jugador: unMazo
user -> juego: iniciarJuego()

juego --> ronda**: Ronda(Jugador)
juego -> ronda: iniciarRonda()
ronda -> jugador: iniciarRonda()
jugador -> mazo: cartasSuficientes()
mazo --> jugador: true

jugador --> user
@enduml