@startuml
'https://plantuml.com/sequence-diagram

title Se verifica que se respeta el orden en la puntuación de las cartas.


actor ":TestCase" as user
participant "cartas: List<CartaPoker>" as cartas
participant ":Jugada" as jugada
participant "jugada: FullHouse" as fullHouse

user -> cartas**: <<create>>

user -> jugada**: crearJugada(cartas)

loop itera hasta que esJugada sea true
    jugada -> jugada: esJugada(cartas)
end
note left
    empezando en EscaleraReal y terminando en
    CartaAlta, cada subclase de Jugada comprueba
    si las cartas forman una mano de poker
end note

jugada -> fullHouse**: new(cartas)

user -> fullHouse: isInstanceOf(Trio)
fullHouse --> user: false
user -> fullHouse: isInstanceOf(Par)
fullHouse --> user: false
user -> fullHouse: isInstanceOf(FullHouse)
fullHouse --> user: true

@enduml