@startuml
'https://plantuml.com/sequence-diagram

title Se verifica que a un jugador se le reparten 8 cartas de su mazo

actor ":TestCase" as user
participant ":Ronda" as ronda
participant ":Jugador" as jugador
participant ":Mazo" as mazo
participant ":Mano" as mano

user -> jugador**: Jugador(Roberto)
    jugador --> mazo **: Mazo()

user --> ronda**: Ronda(Jugador)

user -> ronda: iniciarRonda()
    ronda -> jugador: iniciarRonda()
        jugador -> mazo: repartir()
            mazo -> mazo: rellenar(8)
                loop hasta cantidad = 8
                    mazo -> mazo: darCarta(): CartaPoker
                end
            mazo --> mazo: cartasRepartidas
        mazo -> mano**: Mano(cartasRepartidas)
user -> jugador: esManoLlena()
    jugador -> mano: manoLlena()
    mano --> jugador: true
jugador --> user: true
@enduml