@startuml
'https://plantuml.com/sequence-diagram

title Se verifica que se puede jugar una mano de un mazo

actor ":TestCase" as user
participant ":Jugador" as jugador
participant ":Mazo" as mazo
participant ":Mano" as mano

user -> jugador**: Jugador(Javier)
user -> mazo**: Mazo()
user -> mazo: repartir()
    mazo -> mazo: rellenar(8)
                loop hasta cantidad = 8
                    mazo -> mazo: darCarta(): CartaPoker
                end
    mazo --> mazo: cartasRepartidas
    mazo -> mano**: Mano(cartasRepartidas)
mazo --> user: unaMano
user -> jugador: setMano(unMano)
user -> jugador: jugar()
jugador --> user: unaJugada
@enduml