@startuml
'https://plantuml.com/sequence-diagram

title Se verifica que a un jugador se le reparten 8 cartas de su mazo

actor ":TestCase" as user
participant ":Juego" as juego
participant ":Ronda" as ronda
participant ":Jugador" as jugador
participant ":Mazo" as mazo
participant ":Mano" as mano

user -> juego**: Juego(nombreJugador)
juego -> jugador**: Jugador(nombreJugador)
jugador --> mazo **: Mazo()
mazo --> jugador: unMazo
user -> juego: iniciarJuego()

juego --> ronda**: Ronda(Jugador)
juego -> ronda: iniciarRonda()
ronda -> jugador: repartir()
jugador -> mazo: repartir()
mazo -> mano **: Mano()
mano -> mano: rellenar()
loop hasta cantidad = 8
    mano -> mazo: darCarta()
    mazo --> mano: CartaPoker
end
mano --> mazo: unaMano
mazo --> jugador: unaMano
jugador -> mano: manoLlena()
mano --> jugador: true
jugador --> user
@enduml