@startuml
'https://plantuml.com/sequence-diagram

title Se verifica que al jugar una mano, se aplique el valor correspondiente.

actor ":TestCase" as user
participant ":Jugada" as jugada
participant ":CartaPoker" as cartaPoker
participant ":CartaAlta" as cartaAlta

user -> jugada: crearJugada(cartas)
    loop iteracion hasta encontrar posible jugada
        jugada -> jugada: esJugada(cartas)
    end
    note left
        Si no encuentra ninguna jugada, se devuelve una instancia de CartaAlta.
    end note
    jugada -> cartaAlta**: CartaAlta(cartas)
        cartaAlta -> cartaAlta: encontrarCartaAlta(cartas)
            cartaAlta -> cartaPoker**: CartaPoker(cartaPoker)
            loop iteracion hasta encontrar la carta de mayor valor
                cartaAlta -> cartaPoker: esmayorA(carta)
                cartaPoker --> cartaAlta: true
            end
cartaAlta --> user: cartaAlta

user -> jugada: calcularPuntaje()
    jugada -> cartaAlta: calcularPuntaje()
        cartaAlta -> cartaPoker: calcularPuntaje()
            cartaPoker -> puntaje: calcularPuntaje()
            puntaje --> cartaPoker: unNumero
        cartaPoker --> cartaAlta: unNumero
    cartaAlta --> jugada: unNumero
jugada --> user: unNumero
@enduml