@startuml
'https://plantuml.com/sequence-diagram

actor Usuario as user
participant ":Juego" as juego
participant ":Ronda" as ronda
participant ":Jugador" as jugador
participant ":Mazo" as mazo
participant "m: Mano" as mano

user -> juego**: Juego()
user -> jugador**: Jugador(nombre)
user -> juego: añadirJugador(Jugador)

jugador --> mazo **: Mazo()
mazo --> jugador: unMazo
user -> juego: iniciarJuego()

juego -> ronda**: Ronda(Jugador)
juego -> ronda: iniciarRonda()
ronda -> jugador: repartir()
jugador -> mazo: repartir()
mazo --> mano**: Mano(Lista<CartasPoker>)
mazo --> jugador:(m)

jugador -> mano: seleccionarCartas()
mano --> jugador: seleccionadas
jugador -> ":Poker" as jugada**: Jugada(seleccionadas)
jugador -> ronda: jugar(poker)

ronda -> jugada: Puntuacion()
jugada --> ronda: unaPuntuacion

ronda -> juego: unaPuntuacion
@enduml